# Generated by Django 4.0.5 on 2022-06-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utenti', '0003_rename_vendor_ecommerceuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceuser',
            name='isVendor',
            field=models.BooleanField(default=False),
        ),
    ]
