# Generated by Django 4.0.5 on 2022-06-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_utenti', '0004_ecommerceuser_isvendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecommerceuser',
            options={'verbose_name_plural': 'Utenti'},
        ),
    ]
