# Generated by Django 4.0.5 on 2022-06-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prodotti', '0005_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
