# Generated by Django 4.0.5 on 2022-06-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prodotti', '0012_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
