# Generated by Django 4.0.5 on 2022-06-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prodotti', '0014_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='text',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
