# Generated by Django 4.0.5 on 2022-06-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prodotti', '0017_alter_score_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
