# Generated by Django 4.0.5 on 2022-06-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_utenti', '0005_alter_ecommerceuser_options'),
        ('app_prodotti', '0022_vendorscore_vendor_alter_productscore_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorscore',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor', to='app_utenti.ecommerceuser'),
        ),
    ]
