# Generated by Django 4.0.5 on 2022-06-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prodotti', '0023_alter_vendorscore_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorscore',
            options={'verbose_name_plural': 'Recensioni - Venditori'},
        ),
        migrations.RemoveField(
            model_name='vendorscore',
            name='text',
        ),
    ]
