# Generated by Django 4.0.5 on 2022-06-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_utenti', '0005_alter_ecommerceuser_options'),
        ('app_prodotti', '0024_alter_vendorscore_options_remove_vendorscore_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prodotti.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_utenti.ecommerceuser')),
            ],
            options={
                'verbose_name_plural': 'Ordini',
            },
        ),
    ]
