# Generated by Django 4.0.5 on 2022-06-22 13:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_utenti', '0005_alter_ecommerceuser_options'),
        ('app_prodotti', '0027_alter_orders_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.datetime(2022, 6, 22, 13, 53, 0, 175128, tzinfo=utc))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prodotti.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_utenti.ecommerceuser')),
            ],
            options={
                'verbose_name_plural': 'Ordini',
            },
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
