# Generated by Django 4.0.5 on 2022-07-03 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prodotti', '0030_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
