# Generated by Django 4.0.5 on 2022-07-03 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prodotti', '0031_order_order_type_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notification',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
