# Generated by Django 4.0.5 on 2022-07-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prodotti', '0032_order_notification_alter_order_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notification',
        ),
    ]
